version: '3.8'

services:
  anonamebot:
    build: .
    container_name: anonamebot
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/healthz', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem
    read_only: true
    # Temporary filesystem for writable areas
    tmpfs:
      - /tmp
      - /var/run
